import uuid from 'react-native-uuid'; //  npm install react-native-uuid

// uuid: Biblioteca usada para gerar hashs e ids

export default [
    {id: uuid(), task: 'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    /*{id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false},
    {id: uuid(), task:'Fazer XYZ', done:false},
    {id: uuid(), task:'Fazer ABC', done:true},
    {id: uuid(), task:'Fazer YUI', done:false}*/
];